-- Add created_at column to all tables with DEFAULT NOW()
ALTER TABLE households ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE cycles ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE categories ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE expenses ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE expense_splits ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
